### ISSUE TITLE
Most of the ZKM obfuscator executions are failing

### ISSUE THREAD

**Issue by VenTaz** [GraxCode/threadtear#15]
Only the try-catch blocks removing seems to be working.

JAR : https://gofile.io/d/cnIUtw

Logger: https://throwbin.io/STvWWSt

 - OS: Windows 10
 - Java version: 8

**Comment by GraxCode** [comment]
Try again.

**Comment by VenTaz** [comment]
I did it, and now I have some problems with the class version, is it due to ZKM ?

https://throwbin.io/7NuSlas

**Comment by GraxCode** [comment]
Try to install latest java 8 or even use a newer major java version

**Comment by VenTaz** [comment]
Works perfectly
