### ISSUE TITLE
Does ZKM work for 14.0.5?

### ISSUE THREAD

**Issue by Cryfix** [GraxCode/threadtear#17]
Hi, Does ZKM work for 14.0.5? I really need.

**Comment by GraxCode** [comment]
It should work, if it's not DES cipher mode. Try it out yourself

**Comment by Cryfix** [comment]
> It should work, if it's not DES cipher mode. Try it out yourself

I tried but it didn't work. Would you try for me?

**Comment by GraxCode** [comment]
Sure, if you have the rights for the jar. If you don't want to share it publicly you can add me on discord

**Comment by Cryfix** [comment]
> Sure, if you have the rights for the jar. If you don't want to share it publicly you can add me on discord

What's your Discord name?
Add me : Cryfix#9999

**Comment by Cryfix** [comment]
> Sure, if you have the rights for the jar. If you don't want to share it publicly you can add me on discord

I have been waiting for 1 day.

**Comment by GraxCode** [comment]
Closing this as it is a duplicate of #10
