### ISSUE TITLE
private constructors for utilities

### ISSUE THREAD

**Issue by awesomennguy** [GraxCode/threadtear#22]
title says all ^^

**Comment by GraxCode** [comment]
I'm not exactly sure what you mean. Are some constructors private and you want me to make them public? If yes, please link the class(es).

**Comment by awesomennguy** [comment]
I mean you should add private constructors for utilities & make the class final, for example https://github.com/GraxCode/threadtear/blob/master/src/me/nov/threadtear/util/Counting.java , it doesn't have private constructor and it isnt final.

**Comment by GraxCode** [comment]
I see.
