### ISSUE TITLE
Licenses aren't included in fat jar.

### ISSUE THREAD

**Issue by weisJ** [GraxCode/threadtear#27]
Currently the `fatJar` task simply copies the content of each dependency into the jar. This results in files that have the same name to be overwritten.
Because most licenses are located at (and called) `META-INF/LICENSE` only one of those will survive (which isn't event deterministic.

I see two possible solutions here.

1. Switch to a plugin which handles the creation of the fat jar e.g. [shadow](https://github.com/johnrengelman/shadow) and configure it to copy the contents of the `META-INF` folder of each jar to `META-INF/<dependency-name>`.

2. Switch from `java-library` to `the `application` plugin. The `application` plugin creates a distribution zip which contains all jar files and a startup script.
   ````groovy
   plugins {
       id 'application'
   }
   
   application {
       mainClassName = 'me.nov.threadtear.Threadtear'
       applicationName = 'Threadtear'
   }
   ````
   The resulting zip has the following structure.
   ````
    Threadtear-2.7.0/
    ├── bin/    // This is also the working directory for the application.
    │   ├── Threadtear
    │   └── Threadtear.bat
    └── lib/
         ├── ...
         └── all dependencies
   ````

**Comment by GraxCode** [comment]
Actually, gradle puts all of the license files inside the jar file without any problems, as duplicate zip entries are allowed (not in java though). But you are right, it would be nice to know from which library they come from. I really don't like the idea of making threadtear an application as in my opinion a standalone .jar file is much more compact than a folder with bin, lib, etc.

**Comment by weisJ** [comment]
> Actually, gradle puts all of the license files inside the jar file without any problems, as duplicate zip entries are allowed (not in java though). 

I don’t see this reflected in the resulting fat jar. There are still licenses that are missing.

**Comment by GraxCode** [comment]
![Screenshot_24](https://user-images.githubusercontent.com/24767548/84579102-7f10df80-adcb-11ea-9b8a-899c2988274b.png)
(using WinRAR)

**Comment by weisJ** [comment]
I was using the archive view in IntelliJ, which apparently doesn’t show duplicate files. I still think it would be nice to remove the ambiguity between the licenses. One shouldn’t be forced to use a certain program to view the licenses.

**Comment by GraxCode** [comment]
Of course, that's what i also think. Will probably use shadow to handle that.

**Comment by weisJ** [comment]
With #26 I have implemented merging of unique licenses with the same name into one file. I think for now this is the best one can do with the shadow plugin, as neither the relocators nor the transformers get information about the original dependency a file comes from.

**Comment by GraxCode** [comment]
Should this be closed?

**Comment by weisJ** [comment]
Can be closed. If the shadow plugin ever gets updated to include dependency information for files the current approach can be improved.
