### ISSUE TITLE
IllegalArgumentException thrown when loading a jar file

### ISSUE THREAD

**Issue by iamkyaru** [GraxCode/threadtear#32]
**Describe what's not working**
An IllegalArgumentException is thrown when loading any jar file.

**Java archive**
Not jar-speficic.

**Log / Screenshots**
https://pastebin.com/unFzRRAV

**Please complete the following information:**
 - OS: Windows 10
 - Java version: 1.8.0_252

**Comment by iamkyaru** [comment]
Okay, the exception is only thrown when running the project without Gradle.

**Comment by GraxCode** [comment]
The bug should have been fixed already, maybe check if it is the latest version / somehow cached? Maybe try to reimport the project.

**Comment by GraxCode** [comment]
Is this still an issue?

**Comment by iamkyaru** [comment]
No, not anymore.
