### ISSUE TITLE
Stringer deobfuscation error

### ISSUE THREAD

**Issue by nedogimov** [GraxCode/threadtear#36]
**Describe what's not working**
Do not decrypt strings and a bunch of errors

**Java archive**
https://yadi.sk/d/webOy19cVkmYtw

**Log / Screenshots**
https://pastebin.com/mxr4g22E

**Please complete the following information:**
 - OS: Windows 10 Pro
 - Java version: 8.251

**Comment by GraxCode** [comment]
There are no obfuscated strings in this file, and the file probably wasn't even obfuscated with stringer. Also it looks like it was reobfuscated.
