### ISSUE TITLE
About unused code in the project.

### ISSUE THREAD

**Issue by tjrbrom** [GraxCode/threadtear#38]
Hi guys, I thought I should open an issue for that:

There are so many **unused declarations** in your project, be it methods, unused imports, global fields etc.

![Capture](https://user-images.githubusercontent.com/29039541/87849611-9a06d000-c8f2-11ea-95f2-1713ddcfd3a8.PNG)

Is this done on purpose / am I missing something? Or is this "unused" code being loaded at Runtime indirectly (maybe with reflection?) 

Any reply is appreciated, thanks.

**Comment by GraxCode** [comment]
Some code snippets have been inherited from my older projects and I left them in mostly on purpose, as it makes creation of Executions easier. I consider them as library methods, but if you find methods that are really unnecessary, let me know.

**Comment by GraxCode** [comment]
I have removed all members that are unnecessary and not relevant for library-usage.
