### ISSUE TITLE
Please see.

### ISSUE THREAD

**Issue by Cryfix** [GraxCode/threadtear#40]
Can you tell me what is this protected with? 
And if it is not difficult, will you crack it?
Discord: exotic.# 0001
If you crack software, contact me from discord. I would like to give a gift.

**Comment by Cryfix** [comment]
Crack me : https://s4.dosya.tc/server11/xdr42n/crack_me.rar.html

**Comment by GraxCode** [comment]
Hey there, haven't taken a look at it, but CrackMes are usually obfuscated manually to make it especially hard to understand it.

**Comment by iamkyaru** [comment]
It looks like ZKM to me.

**Comment by ThisTestUser** [comment]
Looking at the constant pool, it seems to be obfuscated with the evaluation version of ZKM 14.0.1.

**Comment by Cryfix** [comment]
> Hey there, haven't taken a look at it, but CrackMes are usually obfuscated manually to make it especially hard to understand it.

My previous discord account was closed. Please write me ?
My new discord account: exotic.# 0001

**Comment by Cryfix** [comment]
> Looking at the constant pool, it seems to be obfuscated with the evaluation version of ZKM 14.0.1.

Can you write me a message from discord?
exotic.#0001
