### ISSUE TITLE
ZipInflator spoof

### ISSUE THREAD

**Issue by Mysels** [GraxCode/threadtear#42]
Tremendous ZipEntry
https://anonymousfiles.io/HZoHJcm8/

**Comment by Mysels** [comment]
not a bug.Just help wanted.

**Comment by Col-E** [comment]
Additionally, this uses bloated annotations that are small in class file representation, and are easily compacted. But when represented in ASM each annotation has to create a string with the long value. This is done 32 or so times on a dozen fields/methods causing excess of 8 GB to be used _(I ran out at that point)_

A partial solution is to parse this with a lower level class file library, detect the obviously ill-intended long string, and remove any reference to it _(In this case, just annotations)_.

Then you can edit the constant pool entry itself to make it smaller.

**Comment by Mysels** [comment]
@Col-E Thanks.Maybe we could load it into JVM and dump it out with sa-jdi tool?
