### ISSUE TITLE
Failed to load class

### ISSUE THREAD

**Issue by Xed0sS** [GraxCode/threadtear#45]
I try to decompile this class, but I get ERROR: Failed to load class  (java.lang.ArrayIndexOutOfBoundsException: 64218)
Class: https://www.upload.ee/files/12345161/hS.class.html

**Comment by nedogimov** [comment]
> I try to decompile this class, but I get ERROR: Failed to load class  (java.lang.ArrayIndexOutOfBoundsException: 64218)
> Class: https://www.upload.ee/files/12345161/hS.class.html

This asm crash obfuscator

**Comment by Xed0sS** [comment]
> > I try to decompile this class, but I get ERROR: Failed to load class  (java.lang.ArrayIndexOutOfBoundsException: 64218)
> > Class: https://www.upload.ee/files/12345161/hS.class.html
> 
> This asm crash obfuscator
Can you send a link to this shit?

**Comment by nedogimov** [comment]
> 
> > This asm crash obfuscator
> 
> Can you send a link to this shit?

It's private obfuscator and i dont have it

**Comment by GraxCode** [comment]
Not a threadtear bug - ASM related
