### ISSUE TITLE
Not work with BinSecure

### ISSUE THREAD

**Issue by Rabbit0w0** [GraxCode/threadtear#50]
I tried to drag a binsecure obfuscated jar into it but it just displayed errors.
are there any patch work with binsecure?

**Comment by Crystallinqq** [comment]
post jar

**Comment by GraxCode** [comment]
BinSecure uses an ASM related bug, not related to threadtear.

**Comment by x4e** [comment]
:/

**Comment by Col-E** [comment]
Since this is closed, gonna plug a WIP project: https://github.com/Col-E/CAFED00D/
 - Goal is to be able to read classes that crash ASM and automatically remove the malformed attributes. 

Could be used when its more fleshed out.

**Comment by fee1-dead** [comment]
How do I make work with binsecure?

**Comment by Crystallinqq** [comment]
@fee1-dead free binscure deobfuscate 2020 no virus now?

**Comment by fee1-dead** [comment]
How

**Comment by x4e** [comment]
dont...
