### ISSUE TITLE
Allatori string decryption bug

### ISSUE THREAD

**Issue by fikawka** [GraxCode/threadtear#59]
Hello i have been trying to deobfuscate one jar file.
its mixed and i got everything from it except strings which are pretty important for me
so it says:
Of a total 274 encrypted strings, 0.0% were successfully decrypted 

So it knows they are encrypted, and they look like allatori.
Above that it spams this:

Failed to decrypt string in Class329._congo()V: java.lang.reflect.InvocationTargetException, nul
its always the same bug, only other class.

**Comment by JohnShiozo** [comment]
please attach a sample jar if possible

**Comment by GraxCode** [comment]
This is probably because Allatori needs the original method names to decrypt strings. Make sure to  reobfuscate it after decrypting.
