### ISSUE TITLE
Binscure Obfuscator Support

### ISSUE THREAD

**Issue by xxxOMA** [GraxCode/threadtear#60]
https://binclub.dev/binscure

Binscure is a obfuscator developed by mastercooker.

**Comment by Col-E** [comment]
#58 
#50 

Threadtear has previously closed issues regarding this. However, if you plop them into [Recaf](https://github.com/Col-E/Recaf) and export them back, Recaf will strip out the parts that crash ASM, allowing Threadtear to work on the jar again.

**Comment by GraxCode** [comment]
Will not fix ASM crashing, but binscure's normal obfuscation techniques are not that good, so some of it can definitely be deobfuscated using generic executions.
