### ISSUE TITLE
Needing Help With Detecting And Deobfuscating!

### ISSUE THREAD

**Issue by jiggey1** [GraxCode/threadtear#61]
I am using Threadtear to deobfuscate some annoying Java code. There are around 2,700 class files (all encrypted with random ass names like _ab2) Most of them look the same as in the screenshot. I am 65% sure that this is ZKM but honestly i'm not sure since I primarily deobf C# and .NET files. Any help is greatly appreciated!

![Screenshot 2021-04-16 022201](https://user-images.githubusercontent.com/70109562/114958305-99d43a80-9e5a-11eb-9618-400266caa500.png)
![Screenshot 2021-04-16 022211](https://user-images.githubusercontent.com/70109562/114958306-9a6cd100-9e5a-11eb-90c3-d6ea508b620a.png)
![Screenshot 2021-04-16 022224](https://user-images.githubusercontent.com/70109562/114958307-9b056780-9e5a-11eb-9e8a-c6285ba59443.png)
![Screenshot 2021-04-16 022512_LI](https://user-images.githubusercontent.com/70109562/114958574-33035100-9e5b-11eb-9bb0-ee2753ee9823.jpg)

*These three screenshots are from ONE file. The others look the same but are sometimes alot longer or alot shorter.

**Comment by iamkyaru** [comment]
This looks like plain old ZKM flow obfuscation. You can use the "try catch obfuscation remover" execution with the "obvious flow obfuscation" execution to deobfuscate your jar file.

**Comment by jiggey1** [comment]
> This looks like plain old ZKM flow obfuscation. You can use the "try catch obfuscation remover" execution with the "obvious flow obfuscation" execution to deobfuscate your jar file.

I appreciate the reply! unfortunately my attempt went unsuccessful. Any other suggestions? If not i completely understand!

**Comment by jiggey1** [comment]
> This looks like plain old ZKM flow obfuscation. You can use the "try catch obfuscation remover" execution with the "obvious flow obfuscation" execution to deobfuscate your jar file.

I realized why this cant be deobfuscated. It's encrypted using DES Cipher and I'm not sure Threadtear supports this yet. Please correct me if i'm wrong but for now, i guess I need to wait.
