### ISSUE TITLE
help

### ISSUE THREAD

**Issue by GloriousBreenie** [GraxCode/threadtear#63]
![image](https://user-images.githubusercontent.com/80313057/118000190-07429080-b35f-11eb-92c8-e50b9522ccf6.png)
I can't open it and there's error! Can you help  me with this, plz

**Comment by Col-E** [comment]
Use Java 8

**Comment by GloriousBreenie** [comment]
![image](https://user-images.githubusercontent.com/80313057/118013702-da48aa80-b36b-11eb-82e8-3cd803a890fe.png)

**Comment by x4e** [comment]
Run `java -version` in powershell

**Comment by GloriousBreenie** [comment]
oh it's 16 at this point
![image](https://user-images.githubusercontent.com/80313057/118014520-be91d400-b36c-11eb-9f72-36ca20b18642.png)

**Comment by x4e** [comment]
Yes. Change it to 8.

**Comment by GloriousBreenie** [comment]
i just need delete this and then download 8, yes? Or i can just switch it somehow without deleting anything?

**Comment by GloriousBreenie** [comment]
It maybe pretty stupid question but i don't know honestly

**Comment by Col-E** [comment]
Just update your path in windows so it has only one directory for Java, for JDK 8.
No need to uninstall anything,

**Comment by GloriousBreenie** [comment]
Ah, thanks, i'll try it later and will send u a result

**Comment by GloriousBreenie** [comment]
![image](https://user-images.githubusercontent.com/80313057/118025018-cce5ed00-b378-11eb-88df-c1eb002f02c9.png)
It's working !

**Comment by GloriousBreenie** [comment]
Thanks for helping me and have a good day
