### ISSUE TITLE
UI improvements.

### ISSUE THREAD

**Issue by weisJ** [GraxCode/threadtear#8]
Some recommendations for improving the UI.

- Don’t put buttons in a `GridLayout`. It ignores their preferred size and makes them too large. Consider using a `Box` with glues and spacers for positioning or wrap each button inside a `JPanel` with `GridBagLayout` and `null` constraints.

Some points regarding `darklaf`
- there is a new version out: `2.0.2`
- Consider replacing the lowered and raised borders with `DarkBorders#createLineBorder‘
- Consider adding the option to change the theme to one of the other variant. You can use the  `ThemeSettings` class to achieve this without much work.
- As you are using Icons from the IntelliJ suit you might want to change them to `.svg` format (available on the IntelliJ community repo) and load them using `IconLoad#loadIcon`.
    - You’ll need to include `darklaf-property-loader` for this.
    - As IntelliJ offers light and dark icons you can also load an icon with a dark and light variant.
        - However the recommended approach for `darklaf` is to use `ThemedSVGIcon` with the provided properties. (If you want I can help converting the icons to the correct format).

**Comment by GraxCode** [comment]
Hey weisJ, thanks for your suggestions. I can't seem to find version 2.0.2 on maven. Also `DarkBorders#createLineBorder` does nothing for me, it displays no border (could be the old version). I can't really fulfill your recommendations without a newer version on maven.

**Comment by weisJ** [comment]
> I can't seem to find version 2.0.2 on maven. 

The artifact was renamed to `darklaf-core` a few versions ago. See https://github.com/weisJ/darklaf/blob/master/README.md#artifacts .

> Also `DarkBorders#createLineBorder` does nothing for me, it displays no border (could be the old version).

It is due to the old version.

**Comment by GraxCode** [comment]
I have switched to the latest version, and I can see that a few things have changed. But what happened to the separator? http://prntscr.com/s2cupr Also is there a way to disable those vertical lines on the divider?

**Comment by GraxCode** [comment]
In terms of icons i can't seem to find the icons i need. It's just too big. Do you know the location where they could be?

**Comment by weisJ** [comment]
> I have switched to the latest version, and I can see that a few things have changed. But what happened to the separator? http://prntscr.com/s2cupr Also is there a way to disable those vertical lines on the divider?

The line have been added as most use cases require them to be present. What you can do is replace it with a single line
````
splitpane.putClientProperty("JSplitPane.style", "line");
````
or make it invisible
````
splitpane.putClientProperty("JSplitPane.style", "line");
````
and add manual spacing between the left and right component,

>In terms of icons i can't seem to find the icons i need. It's just too big. Do you know the location where they could be?

They are located [here](https://github.com/JetBrains/intellij-community/tree/master/platform/icons/src/)

**Comment by GraxCode** [comment]
I already browsed that icon path, didn't find them :/ I also noticed that the gap between the left side and the frame icon is smaller, is it possible to revert this change?

**Comment by weisJ** [comment]
[class](https://github.com/JetBrains/intellij-community/blob/master/platform/icons/src/nodes/class.svg),[enum](https://github.com/JetBrains/intellij-community/blob/master/platform/icons/src/nodes/enum.svg),[folder](https://github.com/JetBrains/intellij-community/blob/master/platform/icons/src/nodes/folder.svg),[field](https://github.com/JetBrains/intellij-community/blob/master/platform/icons/src/nodes/field.svg),[interface](https://github.com/JetBrains/intellij-community/blob/master/platform/icons/src/nodes/interface.svg),[method](https://github.com/JetBrains/intellij-community/blob/master/platform/icons/src/nodes/method.svg),[package](https://github.com/JetBrains/intellij-community/blob/master/platform/icons/src/nodes/package.svg)

I'm not quite sure about the "execution_*" icons. Did you make them yourself? Are they base off any intellij icons (if yes where are they visible).

**Comment by GraxCode** [comment]
They are based on the schema icon (https://resources.jetbrains.com/help/img/idea/2020.1/database-openapi.icons.schema@2x.png). Thanks for your help!

**Comment by weisJ** [comment]
https://jetbrains.design/intellij/resources/icons_list/

Search -> "Schema"

**Comment by weisJ** [comment]
>I also noticed that the gap between the left side and the frame icon is smaller

Good catch!

> is it possible to revert this change?

Yes :D

**Comment by GraxCode** [comment]
How? Also you mistakenly put the line `splitpane.putClientProperty("JSplitPane.style", "line");` twice, what would be the other case where i hide it? And is the thing with the JSeparator a bug? (https://prnt.sc/s2cupr)

**Comment by GraxCode** [comment]
It also seems like `JTextArea.setMargin` is not working anymore.

**Comment by weisJ** [comment]
> How? Also you mistakenly put the line `splitpane.putClientProperty("JSplitPane.style", "line");` twice, what would be the other case where i hide it? 

It should have been `"invisible"` the second time. In the next version (should be tomorrow) you'll be able to specify `"gripBorderless"` which reproduces the old behaviour.

>And is the thing with the JSeparator a bug? (https://prnt.sc/s2cupr)

Not really a bug. Separators are really intended to be used in Toolbars etc.. They aren't an replacement for borders. Nonetheless I have adjusted them to paint the whole space they occupy.

> It also seems like JTextArea.setMargin is not working anymore

Fixed (with next version)

> add a border to JDialogs if possible http://prntscr.com/s2hhkc

Not really possible. What did you do to achieve that the windows doesn't have a shadow.

**Comment by weisJ** [comment]
If you really want to have the border you can use `LafManager#registerInitTask` in which you set the `"RootPane.dialogBorder"` property.

**Comment by GraxCode** [comment]
I think the shadow looks better, but why is it not displaying?
