### ISSUE TITLE
Build failed (no such symbol: IconLoader)

### ISSUE THREAD

**Issue by skidunion** [GraxCode/threadtear#9]
**Describe what's not working**
Can't build the app when I cloned it
Command: gradle fatJar

**Log / Screenshots**
https://hasteb.in/josofoko.gradle

**Please complete the following information:**
 - OS: Windows 10
 - Java version: Java 8_231

**Comment by GraxCode** [comment]
This is really weird, as it happens for me too, but in eclipse itself it starts flawlessly.

**Comment by GraxCode** [comment]
@weisJ do you know why this happens? Am I using the wrong dependencies?

**Comment by weisJ** [comment]
You will need to include the dependencies explicitly in gradle.
````
compile 'com.github.weisj:darklaf-core:2.0.3'
compile 'com.github.weisj:darklaf-theme:2.0.3'
compile 'com.github.weisj:darklaf-property-loader:2.0.3'
````

**Comment by GraxCode** [comment]
Thanks!
